/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Math */

#ifndef _Included_Math
#define _Included_Math
#ifdef __cplusplus
extern "C" {
#endif
#undef Math_PI
#define Math_PI 3.141592653589793
/*
 * Class:     Math
 * Method:    pow
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Math_pow
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     Math
 * Method:    floor
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Math_floor
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     Math
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Math_sqrt
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
