// C++
#include <vector>
#include <list>
#include <deque>
#include <queue>
#include <map>
#include <set>
#include <algorithm>
#include <string>
#include <iostream>
#include <tr1/unordered_map>
#include <tr1/unordered_set>

// C
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <limits.h>
#include <ctype.h>
#include <stdio.h>
#include <stdarg.h>
#include <stddef.h>
#include <math.h>
#include <setjmp.h>
#include <signal.h>

// C99
#include <inttypes.h>
