#!/usr/bin/env sh

#java -cp bin Health -l 1 -t 7 -s 1 -m
#java -cp bin Health -l 1 -t 16 -s 1 -m
java -cp bin Health -l 2 -t 16 -s 1 -m
#java -cp bin Health -l 3 -t 16 -s 1 -m

#java -cp bin Health -l 5 -t 500 -s 1 -m

