#!/usr/bin/env sh

#minivm -cp bin BH -b 4096 -m
minivm -cp bin BH -b 1 -m
#minivm -cp bin BH -b 2 -m
#minivm -cp bin BH -b 3 -m
#minivm -cp bin BH -b 4 -m
#minivm -cp bin BH -b 5 -m
#minivm -cp bin BH -b 6 -m
#minivm -cp bin BH -b 7 -m
