#!/usr/bin/env sh

#valgrind --leak-check=yes ../../debug/minivm -cp bin Em3d -n 1 -d 1 -m 2> a.txt
#valgrind minivm -cp bin Em3d -n 1 -d 1 -m 2> a.txt
valgrind --leak-check=yes minivm -cp bin Em3d -n 7 -d 1 -m 2> a.txt 1>&2
#valgrind --leak-check=yes minivm -cp bin Em3d -n 3 -d 1 -m 2> a.txt 1>&2
#valgrind --leak-check=yes minivm -cp bin Em3d -n 1 -d 1 -m 2> a.txt 1>&2
#valgrind --leak-check=yes debug/minivm Hello 2>&1 >a.txt

