/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Math */

#ifndef _Included_Math
#define _Included_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Math
 * Method:    sqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Math_sqrt
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
