#!/bin/bash

ropejavac > log-model-$model.txt  2>&1

# x=0
# while [ $x -lt 40 ]
# do
# 	grep -n "#$x" b.txt > b$x.txt
# 	x=`echo "$x + 1" | bc`
# done

#egrep '#5 use spec|#5 spec msg|#5 comt spec|#5 veri spec|#5 reset spec' b.txt > specsnapshot.txt
#egrep '#5 use spec|#5 spec msg|#5 reset spec' specsnapshot.txt > spec.txt
#egrep '#5 comt spec|#5 veri spec|#5 reset spec' specsnapshot.txt > commit.txt

