#!/usr/bin/env bash

. cmd

# 无论是设置LD_LIBRARY_PATH，还是用命令行选项-Djava.library.path，都不起作用。
# 要为native方法加载动态库，只能用System.load，并指明动态库的绝对路径。

#java -Djava.library.path=$ROPEHACKCLASSPATH -ea -cp $ROPECLASSPATH:$ROPEHACKCLASSPATH:bin-javac $APP $PARMS

#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROPEHACKCLASSPATH
#export LD_LIBRARY_PATH=$ROPEHACKCLASSPATH
# LD_LIBRARY_PATH=$ROPEHACKCLASSPATH java -ea -cp $ROPECLASSPATH:$ROPEHACKCLASSPATH:bin-javac $APP $PARMS

java -ea -cp $ROPECLASSPATH:$ROPEHACKCLASSPATH:bin-javac $APP $PARMS



# -ea选项开启java虚拟机的assert功能
